language: groovy
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
before_script:
script: "./travis-build.sh"
env:
  global:
  - secure: lNhWCG7hYPud9Li/H3eB1PQRgOhHP++M8j7Cy2weZ3FEavw6kUByzn+iJrLJjaNZUjt8/JU4Lt54q6dUw2833xShy6Dk5GzoZp4/0nVMmLDCeEoZ2mPfYnm3qvnDMCLTm3xGkjhUrERNsc907A3be32TZ1zmrE1R0nz4mDX1J6c6OJRVzZI6e8hGTKxdTC/2JLiwjUadRPznJFIr/jCrSXy+osEYhfsPFJGWROiGu/coGyPp+u7OCZVTGGYs2S2FlHeR7GIvOCP7/DBOl3Oc9kWchWMnRKDKKulNr/+vyGN6avGRWL+MRBm72edGJu2wHcQC0xTG3ETsMUJzM1ONTjC0MbVOLn9cnkdeuBpZS2BFU/wtfZVRTBib7tKydE6/p1icrrIJEYS8pXc5f6WbsAOoUztGFYpvFLeXzur5OM8QgM4O81Mk4kK3aYlJ3m5Cl18GQLm/DotnpvqU3wZQmPXAFylp7XGQys/gTJZaGYi4LMkilLmh64rQhKYcQeGqWBbcjQtt1sQ5KQpvrmDPEw6Ex1kx5/q7BKOaJhQZB1Xo6DeTdhqz+vX+SUvXrgHJXYvM/Uu99iJFjdRQ1CZHW4BWex2GD3KEP1UMQhRtWfMJaJyz4J65BjeKW/cneONCltC4M5/AlncgKY7fdEfPXHassxlSLbSLL/MfwTZlZ9o=
  - secure: FFaHymQ+3dS40qQW6wnpfKuDupyzerOnEOov6HujZ7pFqJVpOXeeglH9i1E2KITlO+sBRVpuAv7RCu6ACKXSuwxgfDpDcAQKrFGo4vQb/M/yXFElZdT13Uyzz/bST8QibWY4CnLH8h8wVtU58PIPsIg7Dh9prSO+1KeFEjAYt+WVpX2XNoRnuQuEol5cnKBzHpbOLwUDSWb/6iOkXhYYOnUdrFs4DpaL36teckb8wH4w78/7xJrl+D6R4nhIg8r13Iy9RpqJiiow0KWpiP5zVmoF4u9DD4XQjZxeiozwPM0akedE+5lUSL+qCbnhcekRUJSxTov3szF5vVj9wM/Wn2B4nW4SQY0hrEoA7cPiJCSue60IZ4ayRqxhbjMyTamfY4adTg2tQkfyJUs6+dWxobF3nUhCZQFIh5qVh8BQqf5mFzdh3RvJLobcoJ4H3QxRbkSmkiLcb+LWW3bpLWhpVlMrVWx4JqhRg5rdZ3uWsNArqH1s4xKDjYeTM1CiGA5lTvww5uJYo9ydKDxM42h7fVFD7x6OUsQRjvRAru3NURuMuGORz/cRQQz6fJjOyEC1dVM37WkcJ/7fW0ST8ZYYZ5jDooR3Mk4Xlu1pR+ovLGn205ylwSOAUEcWHRTEcAIF2QTq1+PAbe1/Npwwtkr+ro9LrYLTdtu4WSKV74NPyVM=
